-- ============================================================
-- Account Manager model
-- - Posterita staff oversee customer owners without being customer owners
-- - Each customer owner belongs to an account manager
-- ============================================================

CREATE TABLE IF NOT EXISTS account_manager (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    super_admin_id INT REFERENCES super_admin(id) ON DELETE SET NULL UNIQUE,
    auth_uid       UUID REFERENCES auth.users(id) UNIQUE,
    email          TEXT NOT NULL UNIQUE,
    name           TEXT,
    is_active      BOOLEAN DEFAULT TRUE,
    created_at     TIMESTAMPTZ DEFAULT NOW(),
    updated_at     TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE owner
    ADD COLUMN IF NOT EXISTS account_manager_id BIGINT REFERENCES account_manager(id);

CREATE INDEX IF NOT EXISTS idx_owner_account_manager ON owner(account_manager_id);
CREATE INDEX IF NOT EXISTS idx_account_manager_auth_uid ON account_manager(auth_uid);

DROP TRIGGER IF EXISTS set_updated_at_account_manager ON account_manager;
CREATE TRIGGER set_updated_at_account_manager
    BEFORE UPDATE ON account_manager
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

INSERT INTO account_manager (super_admin_id, auth_uid, email, name, is_active)
SELECT
    sa.id,
    sa.auth_uid,
    sa.email,
    sa.name,
    sa.is_active
FROM super_admin sa
ON CONFLICT (email) DO UPDATE
SET
    super_admin_id = EXCLUDED.super_admin_id,
    auth_uid = EXCLUDED.auth_uid,
    name = EXCLUDED.name,
    is_active = EXCLUDED.is_active;

UPDATE owner o
SET account_manager_id = am.id
FROM account_manager am
WHERE o.account_manager_id IS NULL
  AND am.email = 'support@posterita.com';
