-- ============================================================
-- Owner-centric account model
-- - One owner identity per unique email
-- - One owner can manage many accounts
-- - Accounts have explicit type + lifecycle status
-- ============================================================

CREATE TABLE IF NOT EXISTS owner (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_uid     UUID REFERENCES auth.users(id) UNIQUE,
    email        TEXT NOT NULL UNIQUE,
    name         TEXT,
    is_active    BOOLEAN DEFAULT TRUE,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS owner_account_session (
    owner_id     BIGINT PRIMARY KEY REFERENCES owner(id) ON DELETE CASCADE,
    account_id   TEXT NOT NULL REFERENCES account(account_id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE account
    ADD COLUMN IF NOT EXISTS owner_id BIGINT REFERENCES owner(id),
    ADD COLUMN IF NOT EXISTS type TEXT NOT NULL DEFAULT 'live',
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'draft';

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'account_type_check'
    ) THEN
        ALTER TABLE account
            ADD CONSTRAINT account_type_check
            CHECK (type IN ('demo', 'live'));
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'account_status_check'
    ) THEN
        ALTER TABLE account
            ADD CONSTRAINT account_status_check
            CHECK (status IN ('draft', 'in_progress', 'ready', 'failed', 'archived'));
    END IF;
END;
$$;

CREATE INDEX IF NOT EXISTS idx_account_owner ON account(owner_id);
CREATE INDEX IF NOT EXISTS idx_account_type ON account(type);
CREATE INDEX IF NOT EXISTS idx_account_status ON account(status);
CREATE INDEX IF NOT EXISTS idx_owner_auth_uid ON owner(auth_uid);

-- Keep timestamps fresh for the new tables.
DROP TRIGGER IF EXISTS set_updated_at_owner ON owner;
CREATE TRIGGER set_updated_at_owner
    BEFORE UPDATE ON owner
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS set_updated_at_owner_account_session ON owner_account_session;
CREATE TRIGGER set_updated_at_owner_account_session
    BEFORE UPDATE ON owner_account_session
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

-- Backfill owners from existing OWNER pos_user rows.
INSERT INTO owner (auth_uid, email, name, is_active)
SELECT DISTINCT ON (normalized_email)
    auth_uid,
    normalized_email,
    owner_name,
    TRUE
FROM (
    SELECT
        pu.auth_uid,
        LOWER(
            COALESCE(
                NULLIF(BTRIM(pu.email), ''),
                'owner+' || pu.account_id || '@local.posterita.invalid'
            )
        ) AS normalized_email,
        NULLIF(
            BTRIM(
                COALESCE(
                    NULLIF(CONCAT_WS(' ', pu.firstname, pu.lastname), ''),
                    NULLIF(pu.username, ''),
                    NULLIF(a.businessname, ''),
                    'Owner'
                )
            ),
            ''
        ) AS owner_name,
        pu.user_id
    FROM pos_user pu
    LEFT JOIN account a ON a.account_id = pu.account_id
    WHERE LOWER(COALESCE(pu.role, '')) = 'owner'
) source
ORDER BY normalized_email, user_id
ON CONFLICT (email) DO NOTHING;

-- Link each account to its owner when we can infer one.
UPDATE account a
SET owner_id = owner_match.owner_id
FROM (
    SELECT
        a2.account_id,
        o.id AS owner_id
    FROM account a2
    JOIN LATERAL (
        SELECT
            LOWER(
                COALESCE(
                    NULLIF(BTRIM(pu.email), ''),
                    'owner+' || pu.account_id || '@local.posterita.invalid'
                )
            ) AS normalized_email
        FROM pos_user pu
        WHERE pu.account_id = a2.account_id
          AND LOWER(COALESCE(pu.role, '')) = 'owner'
        ORDER BY pu.user_id
        LIMIT 1
    ) inferred_owner ON TRUE
    JOIN owner o ON o.email = inferred_owner.normalized_email
) owner_match
WHERE a.account_id = owner_match.account_id
  AND a.owner_id IS NULL;

-- Normalize legacy account type + status.
UPDATE account
SET type = CASE
    WHEN account_id = 'demo_account' THEN 'demo'
    ELSE 'live'
END;

WITH latest_job AS (
    SELECT DISTINCT ON (account_id)
        account_id,
        status
    FROM ai_import_job
    ORDER BY account_id, updated_at DESC, created_at DESC
)
UPDATE account a
SET status = CASE
    WHEN a.account_id = 'demo_account' THEN 'ready'
    WHEN lj.status = 'processing' THEN 'in_progress'
    WHEN lj.status = 'failed' THEN 'failed'
    WHEN EXISTS (SELECT 1 FROM product p WHERE p.account_id = a.account_id)
      OR EXISTS (SELECT 1 FROM store s WHERE s.account_id = a.account_id)
      OR EXISTS (SELECT 1 FROM orders o WHERE o.account_id = a.account_id)
      THEN 'ready'
    ELSE 'draft'
END
FROM latest_job lj
WHERE a.account_id = lj.account_id;

UPDATE account a
SET status = CASE
    WHEN a.account_id = 'demo_account' THEN 'ready'
    WHEN EXISTS (SELECT 1 FROM product p WHERE p.account_id = a.account_id)
      OR EXISTS (SELECT 1 FROM store s WHERE s.account_id = a.account_id)
      OR EXISTS (SELECT 1 FROM orders o WHERE o.account_id = a.account_id)
      THEN 'ready'
    ELSE 'draft'
END
WHERE NOT EXISTS (
    SELECT 1
    FROM ai_import_job job
    WHERE job.account_id = a.account_id
);

-- Give each owner a default active account so future owner-level switching works.
INSERT INTO owner_account_session (owner_id, account_id)
SELECT DISTINCT ON (owner_id)
    owner_id,
    account_id
FROM account
WHERE owner_id IS NOT NULL
ORDER BY owner_id, created_at DESC, account_id
ON CONFLICT (owner_id) DO NOTHING;

-- Owners can now own multiple accounts, so account resolution should prefer
-- an explicit owner session before falling back to the first pos_user row.
CREATE OR REPLACE FUNCTION public.get_account_id()
RETURNS TEXT AS $$
    SELECT COALESCE(
        current_setting('request.jwt.claims', true)::json->>'account_id',
        (
            SELECT oas.account_id
            FROM owner_account_session oas
            JOIN owner o ON o.id = oas.owner_id
            WHERE o.auth_uid = auth.uid()
              AND o.is_active = TRUE
            LIMIT 1
        ),
        (
            SELECT account_id
            FROM pos_user
            WHERE auth_uid = auth.uid()
            ORDER BY CASE WHEN LOWER(role) = 'owner' THEN 0 ELSE 1 END, user_id
            LIMIT 1
        )
    );
$$ LANGUAGE sql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS TEXT AS $$
    SELECT COALESCE(
        current_setting('request.jwt.claims', true)::json->>'role',
        (
            SELECT role
            FROM pos_user
            WHERE auth_uid = auth.uid()
              AND account_id = public.get_account_id()
            ORDER BY CASE WHEN LOWER(role) = 'owner' THEN 0 ELSE 1 END, user_id
            LIMIT 1
        ),
        (
            SELECT 'OWNER'
            FROM owner
            WHERE auth_uid = auth.uid()
              AND is_active = TRUE
            LIMIT 1
        )
    );
$$ LANGUAGE sql STABLE SECURITY DEFINER;
