-- ============================================================
-- Sync Inbox: stores raw sync payloads for recovery/replay
-- ============================================================
CREATE TABLE IF NOT EXISTS sync_inbox (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id      TEXT NOT NULL,
  terminal_id     INT,
  device_id       TEXT,
  sync_version    INT NOT NULL DEFAULT 0,
  status          TEXT NOT NULL DEFAULT 'received',
  payload         JSONB,
  items_summary   TEXT,
  error_message   TEXT,
  errors          JSONB,
  retry_count     INT NOT NULL DEFAULT 0,
  received_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_sync_inbox_account ON sync_inbox(account_id);
CREATE INDEX IF NOT EXISTS idx_sync_inbox_status ON sync_inbox(status);
CREATE INDEX IF NOT EXISTS idx_sync_inbox_received ON sync_inbox(received_at DESC);

ALTER TABLE sync_inbox ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access on sync_inbox"
  ON sync_inbox FOR ALL
  USING (true)
  WITH CHECK (true);
