-- ============================================================
-- Sync request log: one row per /api/sync POST call
-- ============================================================
CREATE TABLE IF NOT EXISTS sync_request_log (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id      TEXT NOT NULL,
  terminal_id     INT,
  store_id        INT,
  device_id       TEXT,
  device_model    TEXT,
  app_version     TEXT,
  client_sync_version INT,
  request_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  response_at     TIMESTAMPTZ,
  duration_ms     INT,
  status          TEXT NOT NULL DEFAULT 'success',
  error_message   TEXT,
  orders_pushed   INT DEFAULT 0,
  tills_pushed    INT DEFAULT 0,
  customers_pushed INT DEFAULT 0,
  error_logs_pushed INT DEFAULT 0,
  products_pulled INT DEFAULT 0,
  categories_pulled INT DEFAULT 0,
  users_pulled    INT DEFAULT 0,
  stores_pulled   INT DEFAULT 0,
  terminals_pulled INT DEFAULT 0,
  sync_errors     JSONB
);

CREATE INDEX idx_sync_request_log_account ON sync_request_log(account_id);
CREATE INDEX idx_sync_request_log_time ON sync_request_log(request_at DESC);

ALTER TABLE sync_request_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Super admin access sync_request_log" ON sync_request_log
    FOR ALL USING (public.is_super_admin());

NOTIFY pgrst, 'reload schema';
