-- ============================================================
-- CI Report: test results per git push, displayed on platform
-- ============================================================
CREATE TABLE IF NOT EXISTS ci_report (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  git_sha         TEXT NOT NULL,
  branch          TEXT NOT NULL DEFAULT 'main',
  commit_message  TEXT,
  android_passed  INT DEFAULT 0,
  android_failed  INT DEFAULT 0,
  android_files   INT DEFAULT 0,
  web_passed      INT DEFAULT 0,
  web_failed      INT DEFAULT 0,
  web_files       INT DEFAULT 0,
  ts_errors       INT DEFAULT 0,
  status          TEXT NOT NULL DEFAULT 'pass',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ci_report_time ON ci_report(created_at DESC);

ALTER TABLE ci_report ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Super admin access ci_report" ON ci_report
    FOR ALL USING (public.is_super_admin());
-- Also allow service role inserts (CI posts via service key)

NOTIFY pgrst, 'reload schema';
