-- 00058_country_config.sql
-- Regional pricing hardening: country_config table + account.country_code

-- Add country_code to account
ALTER TABLE account ADD COLUMN IF NOT EXISTS country_code TEXT;

-- Create country_config table
CREATE TABLE IF NOT EXISTS country_config (
  country_code TEXT PRIMARY KEY,
  country_name TEXT NOT NULL,
  billing_region TEXT NOT NULL CHECK (billing_region IN ('developing','emerging','developed')),
  currency_code TEXT NOT NULL,
  currency_symbol TEXT DEFAULT '$',
  phone_prefix TEXT,
  modules JSONB DEFAULT '[]'::jsonb,
  timezone TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE country_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service role full access" ON country_config FOR ALL USING (true) WITH CHECK (true);

-- ── Tier 1: Developing ──────────────────────────────────────────
INSERT INTO country_config (country_code, country_name, billing_region, currency_code, currency_symbol, phone_prefix, modules, timezone) VALUES
('AF', 'Afghanistan', 'developing', 'AFN', '؋', '+93', '[]', 'Asia/Kabul'),
('BD', 'Bangladesh', 'developing', 'BDT', '৳', '+880', '[]', 'Asia/Dhaka'),
('BJ', 'Benin', 'developing', 'XOF', 'CFA', '+229', '[]', 'Africa/Porto-Novo'),
('BF', 'Burkina Faso', 'developing', 'XOF', 'CFA', '+226', '[]', 'Africa/Ouagadougou'),
('BI', 'Burundi', 'developing', 'BIF', 'FBu', '+257', '[]', 'Africa/Bujumbura'),
('KH', 'Cambodia', 'developing', 'KHR', '៛', '+855', '[]', 'Asia/Phnom_Penh'),
('CM', 'Cameroon', 'developing', 'XAF', 'FCFA', '+237', '[]', 'Africa/Douala'),
('CF', 'Central African Republic', 'developing', 'XAF', 'FCFA', '+236', '[]', 'Africa/Bangui'),
('TD', 'Chad', 'developing', 'XAF', 'FCFA', '+235', '[]', 'Africa/Ndjamena'),
('KM', 'Comoros', 'developing', 'KMF', 'CF', '+269', '[]', 'Indian/Comoro'),
('CD', 'Congo DR', 'developing', 'CDF', 'FC', '+243', '[]', 'Africa/Kinshasa'),
('CI', 'Côte d''Ivoire', 'developing', 'XOF', 'CFA', '+225', '[]', 'Africa/Abidjan'),
('DJ', 'Djibouti', 'developing', 'DJF', 'Fdj', '+253', '[]', 'Africa/Djibouti'),
('ET', 'Ethiopia', 'developing', 'ETB', 'Br', '+251', '[]', 'Africa/Addis_Ababa'),
('GA', 'Gabon', 'developing', 'XAF', 'FCFA', '+241', '[]', 'Africa/Libreville'),
('GM', 'Gambia', 'developing', 'GMD', 'D', '+220', '[]', 'Africa/Banjul'),
('GH', 'Ghana', 'developing', 'GHS', 'GH₵', '+233', '[]', 'Africa/Accra'),
('GN', 'Guinea', 'developing', 'GNF', 'FG', '+224', '[]', 'Africa/Conakry'),
('HT', 'Haiti', 'developing', 'HTG', 'G', '+509', '[]', 'America/Port-au-Prince'),
('IN', 'India', 'developing', 'INR', '₹', '+91', '[]', 'Asia/Kolkata'),
('ID', 'Indonesia', 'developing', 'IDR', 'Rp', '+62', '[]', 'Asia/Jakarta'),
('KE', 'Kenya', 'developing', 'KES', 'KSh', '+254', '[]', 'Africa/Nairobi'),
('LA', 'Laos', 'developing', 'LAK', '₭', '+856', '[]', 'Asia/Vientiane'),
('LR', 'Liberia', 'developing', 'LRD', 'L$', '+231', '[]', 'Africa/Monrovia'),
('MG', 'Madagascar', 'developing', 'MGA', 'Ar', '+261', '[]', 'Indian/Antananarivo'),
('MW', 'Malawi', 'developing', 'MWK', 'MK', '+265', '[]', 'Africa/Blantyre'),
('ML', 'Mali', 'developing', 'XOF', 'CFA', '+223', '[]', 'Africa/Bamako'),
('MR', 'Mauritania', 'developing', 'MRU', 'UM', '+222', '[]', 'Africa/Nouakchott'),
('MZ', 'Mozambique', 'developing', 'MZN', 'MT', '+258', '[]', 'Africa/Maputo'),
('MM', 'Myanmar', 'developing', 'MMK', 'K', '+95', '[]', 'Asia/Yangon'),
('NP', 'Nepal', 'developing', 'NPR', 'Rs', '+977', '[]', 'Asia/Kathmandu'),
('NE', 'Niger', 'developing', 'XOF', 'CFA', '+227', '[]', 'Africa/Niamey'),
('NG', 'Nigeria', 'developing', 'NGN', '₦', '+234', '[]', 'Africa/Lagos'),
('PK', 'Pakistan', 'developing', 'PKR', 'Rs', '+92', '[]', 'Asia/Karachi'),
('PH', 'Philippines', 'developing', 'PHP', '₱', '+63', '[]', 'Asia/Manila'),
('RW', 'Rwanda', 'developing', 'RWF', 'RF', '+250', '[]', 'Africa/Kigali'),
('SN', 'Senegal', 'developing', 'XOF', 'CFA', '+221', '[]', 'Africa/Dakar'),
('SL', 'Sierra Leone', 'developing', 'SLE', 'Le', '+232', '[]', 'Africa/Freetown'),
('SO', 'Somalia', 'developing', 'SOS', 'Sh', '+252', '[]', 'Africa/Mogadishu'),
('LK', 'Sri Lanka', 'developing', 'LKR', 'Rs', '+94', '[]', 'Asia/Colombo'),
('TZ', 'Tanzania', 'developing', 'TZS', 'TSh', '+255', '[]', 'Africa/Dar_es_Salaam'),
('TG', 'Togo', 'developing', 'XOF', 'CFA', '+228', '[]', 'Africa/Lome'),
('UG', 'Uganda', 'developing', 'UGX', 'USh', '+256', '[]', 'Africa/Kampala'),
('VN', 'Vietnam', 'developing', 'VND', '₫', '+84', '[]', 'Asia/Ho_Chi_Minh'),
('ZM', 'Zambia', 'developing', 'ZMW', 'ZK', '+260', '[]', 'Africa/Lusaka'),
('ZW', 'Zimbabwe', 'developing', 'ZWL', 'Z$', '+263', '[]', 'Africa/Harare')
ON CONFLICT (country_code) DO NOTHING;

-- ── Tier 2: Emerging ────────────────────────────────────────────
INSERT INTO country_config (country_code, country_name, billing_region, currency_code, currency_symbol, phone_prefix, modules, timezone) VALUES
('DZ', 'Algeria', 'emerging', 'DZD', 'DA', '+213', '[]', 'Africa/Algiers'),
('AR', 'Argentina', 'emerging', 'ARS', '$', '+54', '[]', 'America/Buenos_Aires'),
('AM', 'Armenia', 'emerging', 'AMD', '֏', '+374', '[]', 'Asia/Yerevan'),
('AZ', 'Azerbaijan', 'emerging', 'AZN', '₼', '+994', '[]', 'Asia/Baku'),
('BH', 'Bahrain', 'emerging', 'BHD', 'BD', '+973', '[]', 'Asia/Bahrain'),
('BY', 'Belarus', 'emerging', 'BYN', 'Br', '+375', '[]', 'Europe/Minsk'),
('BA', 'Bosnia and Herzegovina', 'emerging', 'BAM', 'KM', '+387', '[]', 'Europe/Sarajevo'),
('BR', 'Brazil', 'emerging', 'BRL', 'R$', '+55', '[]', 'America/Sao_Paulo'),
('BG', 'Bulgaria', 'emerging', 'BGN', 'лв', '+359', '[]', 'Europe/Sofia'),
('CL', 'Chile', 'emerging', 'CLP', '$', '+56', '[]', 'America/Santiago'),
('CN', 'China', 'emerging', 'CNY', '¥', '+86', '[]', 'Asia/Shanghai'),
('CO', 'Colombia', 'emerging', 'COP', '$', '+57', '[]', 'America/Bogota'),
('CR', 'Costa Rica', 'emerging', 'CRC', '₡', '+506', '[]', 'America/Costa_Rica'),
('HR', 'Croatia', 'emerging', 'EUR', '€', '+385', '[]', 'Europe/Zagreb'),
('CZ', 'Czech Republic', 'emerging', 'CZK', 'Kč', '+420', '[]', 'Europe/Prague'),
('DO', 'Dominican Republic', 'emerging', 'DOP', 'RD$', '+1-809', '[]', 'America/Santo_Domingo'),
('EC', 'Ecuador', 'emerging', 'USD', '$', '+593', '[]', 'America/Guayaquil'),
('EG', 'Egypt', 'emerging', 'EGP', 'E£', '+20', '[]', 'Africa/Cairo'),
('GE', 'Georgia', 'emerging', 'GEL', '₾', '+995', '[]', 'Asia/Tbilisi'),
('HU', 'Hungary', 'emerging', 'HUF', 'Ft', '+36', '[]', 'Europe/Budapest'),
('IR', 'Iran', 'emerging', 'IRR', '﷼', '+98', '[]', 'Asia/Tehran'),
('IQ', 'Iraq', 'emerging', 'IQD', 'ع.د', '+964', '[]', 'Asia/Baghdad'),
('JO', 'Jordan', 'emerging', 'JOD', 'JD', '+962', '[]', 'Asia/Amman'),
('KZ', 'Kazakhstan', 'emerging', 'KZT', '₸', '+7', '[]', 'Asia/Almaty'),
('KW', 'Kuwait', 'emerging', 'KWD', 'KD', '+965', '[]', 'Asia/Kuwait'),
('LB', 'Lebanon', 'emerging', 'LBP', 'L£', '+961', '[]', 'Asia/Beirut'),
('LT', 'Lithuania', 'emerging', 'EUR', '€', '+370', '[]', 'Europe/Vilnius'),
('MY', 'Malaysia', 'emerging', 'MYR', 'RM', '+60', '[]', 'Asia/Kuala_Lumpur'),
('MU', 'Mauritius', 'emerging', 'MUR', 'Rs', '+230', '["mra_einvoicing"]', 'Indian/Mauritius'),
('MX', 'Mexico', 'emerging', 'MXN', '$', '+52', '[]', 'America/Mexico_City'),
('MA', 'Morocco', 'emerging', 'MAD', 'MAD', '+212', '[]', 'Africa/Casablanca'),
('OM', 'Oman', 'emerging', 'OMR', 'OMR', '+968', '[]', 'Asia/Muscat'),
('PA', 'Panama', 'emerging', 'PAB', 'B/.', '+507', '[]', 'America/Panama'),
('PE', 'Peru', 'emerging', 'PEN', 'S/', '+51', '[]', 'America/Lima'),
('PL', 'Poland', 'emerging', 'PLN', 'zł', '+48', '[]', 'Europe/Warsaw'),
('QA', 'Qatar', 'emerging', 'QAR', 'QR', '+974', '[]', 'Asia/Qatar'),
('RO', 'Romania', 'emerging', 'RON', 'lei', '+40', '[]', 'Europe/Bucharest'),
('RU', 'Russia', 'emerging', 'RUB', '₽', '+7', '[]', 'Europe/Moscow'),
('SA', 'Saudi Arabia', 'emerging', 'SAR', 'SR', '+966', '[]', 'Asia/Riyadh'),
('RS', 'Serbia', 'emerging', 'RSD', 'din', '+381', '[]', 'Europe/Belgrade'),
('ZA', 'South Africa', 'emerging', 'ZAR', 'R', '+27', '[]', 'Africa/Johannesburg'),
('TH', 'Thailand', 'emerging', 'THB', '฿', '+66', '[]', 'Asia/Bangkok'),
('TN', 'Tunisia', 'emerging', 'TND', 'DT', '+216', '[]', 'Africa/Tunis'),
('TR', 'Turkey', 'emerging', 'TRY', '₺', '+90', '[]', 'Europe/Istanbul'),
('UA', 'Ukraine', 'emerging', 'UAH', '₴', '+380', '[]', 'Europe/Kyiv'),
('UY', 'Uruguay', 'emerging', 'UYU', '$U', '+598', '[]', 'America/Montevideo'),
('UZ', 'Uzbekistan', 'emerging', 'UZS', 'сўм', '+998', '[]', 'Asia/Tashkent'),
('VE', 'Venezuela', 'emerging', 'VES', 'Bs', '+58', '[]', 'America/Caracas')
ON CONFLICT (country_code) DO NOTHING;

-- ── Tier 3: Developed ───────────────────────────────────────────
INSERT INTO country_config (country_code, country_name, billing_region, currency_code, currency_symbol, phone_prefix, modules, timezone) VALUES
('AU', 'Australia', 'developed', 'AUD', 'A$', '+61', '[]', 'Australia/Sydney'),
('AT', 'Austria', 'developed', 'EUR', '€', '+43', '[]', 'Europe/Vienna'),
('BE', 'Belgium', 'developed', 'EUR', '€', '+32', '[]', 'Europe/Brussels'),
('CA', 'Canada', 'developed', 'CAD', 'C$', '+1', '[]', 'America/Toronto'),
('DK', 'Denmark', 'developed', 'DKK', 'kr', '+45', '[]', 'Europe/Copenhagen'),
('FI', 'Finland', 'developed', 'EUR', '€', '+358', '[]', 'Europe/Helsinki'),
('FR', 'France', 'developed', 'EUR', '€', '+33', '[]', 'Europe/Paris'),
('DE', 'Germany', 'developed', 'EUR', '€', '+49', '[]', 'Europe/Berlin'),
('GR', 'Greece', 'developed', 'EUR', '€', '+30', '[]', 'Europe/Athens'),
('HK', 'Hong Kong', 'developed', 'HKD', 'HK$', '+852', '[]', 'Asia/Hong_Kong'),
('IS', 'Iceland', 'developed', 'ISK', 'kr', '+354', '[]', 'Atlantic/Reykjavik'),
('IE', 'Ireland', 'developed', 'EUR', '€', '+353', '[]', 'Europe/Dublin'),
('IL', 'Israel', 'developed', 'ILS', '₪', '+972', '[]', 'Asia/Jerusalem'),
('IT', 'Italy', 'developed', 'EUR', '€', '+39', '[]', 'Europe/Rome'),
('JP', 'Japan', 'developed', 'JPY', '¥', '+81', '[]', 'Asia/Tokyo'),
('KR', 'South Korea', 'developed', 'KRW', '₩', '+82', '[]', 'Asia/Seoul'),
('LU', 'Luxembourg', 'developed', 'EUR', '€', '+352', '[]', 'Europe/Luxembourg'),
('NL', 'Netherlands', 'developed', 'EUR', '€', '+31', '[]', 'Europe/Amsterdam'),
('NZ', 'New Zealand', 'developed', 'NZD', 'NZ$', '+64', '[]', 'Pacific/Auckland'),
('NO', 'Norway', 'developed', 'NOK', 'kr', '+47', '[]', 'Europe/Oslo'),
('PT', 'Portugal', 'developed', 'EUR', '€', '+351', '[]', 'Europe/Lisbon'),
('SG', 'Singapore', 'developed', 'SGD', 'S$', '+65', '[]', 'Asia/Singapore'),
('ES', 'Spain', 'developed', 'EUR', '€', '+34', '[]', 'Europe/Madrid'),
('SE', 'Sweden', 'developed', 'SEK', 'kr', '+46', '[]', 'Europe/Stockholm'),
('CH', 'Switzerland', 'developed', 'CHF', 'CHF', '+41', '[]', 'Europe/Zurich'),
('TW', 'Taiwan', 'developed', 'TWD', 'NT$', '+886', '[]', 'Asia/Taipei'),
('AE', 'UAE', 'developed', 'AED', 'AED', '+971', '[]', 'Asia/Dubai'),
('GB', 'United Kingdom', 'developed', 'GBP', '£', '+44', '[]', 'Europe/London'),
('US', 'United States', 'developed', 'USD', '$', '+1', '[]', 'America/New_York')
ON CONFLICT (country_code) DO NOTHING;
