-- Fraud Prevention: audit event sync + fraud signal detection

-- 1. Server-side audit event table — receives events pushed from Android via sync
CREATE TABLE IF NOT EXISTS audit_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id TEXT NOT NULL,
    timestamp BIGINT NOT NULL DEFAULT 0,
    user_id INTEGER DEFAULT 0,
    user_name TEXT,
    action TEXT NOT NULL,
    detail TEXT,
    reason TEXT,
    supervisor_id INTEGER,
    store_id INTEGER DEFAULT 0,
    terminal_id INTEGER DEFAULT 0,
    order_id TEXT,
    amount DOUBLE PRECISION,
    device_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE audit_event ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_audit_event_account ON audit_event (account_id);
CREATE INDEX IF NOT EXISTS idx_audit_event_action ON audit_event (account_id, action);
CREATE INDEX IF NOT EXISTS idx_audit_event_user ON audit_event (account_id, user_id);
CREATE INDEX IF NOT EXISTS idx_audit_event_created ON audit_event (account_id, created_at DESC);

-- 2. Fraud signal — server-generated anomaly records
CREATE TABLE IF NOT EXISTS fraud_signal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id TEXT NOT NULL,
    store_id INTEGER,
    user_id INTEGER,
    terminal_id INTEGER,
    signal_type TEXT NOT NULL,
    severity TEXT NOT NULL DEFAULT 'warning',
    title TEXT NOT NULL,
    detail TEXT,
    metric_value DOUBLE PRECISION,
    threshold DOUBLE PRECISION,
    period_start TIMESTAMPTZ,
    period_end TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'open',
    resolved_by TEXT,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fraud_signal_severity_check CHECK (severity IN ('info', 'warning', 'critical')),
    CONSTRAINT fraud_signal_status_check CHECK (status IN ('open', 'acknowledged', 'resolved', 'dismissed'))
);

ALTER TABLE fraud_signal ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_fraud_signal_account ON fraud_signal (account_id, status);
CREATE INDEX IF NOT EXISTS idx_fraud_signal_type ON fraud_signal (account_id, signal_type);
CREATE INDEX IF NOT EXISTS idx_fraud_signal_created ON fraud_signal (account_id, created_at DESC);

NOTIFY pgrst, 'reload schema';
