-- Blog posts (AI-generated SEO content)
CREATE TABLE IF NOT EXISTS blog_post (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  meta_description TEXT,
  keyword TEXT,
  html_content TEXT NOT NULL,
  author TEXT DEFAULT 'Posterita Team',
  hero_image_url TEXT,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft','published','archived')),
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Email subscribers
CREATE TABLE IF NOT EXISTS marketing_subscriber (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  name TEXT,
  source TEXT DEFAULT 'website',
  brevo_synced BOOLEAN DEFAULT FALSE,
  drip_step INTEGER DEFAULT 0,
  drip_next_at TIMESTAMPTZ,
  unsubscribed BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Social media posts (AI-generated)
CREATE TABLE IF NOT EXISTS social_post (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  platform TEXT NOT NULL,
  content TEXT NOT NULL,
  post_type TEXT,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft','approved','published','rejected')),
  scheduled_at TIMESTAMPTZ,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Chat messages (AI support)
CREATE TABLE IF NOT EXISTS chat_message (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('user','assistant')),
  content TEXT NOT NULL,
  visitor_email TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Review requests
CREATE TABLE IF NOT EXISTS review_request (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id TEXT NOT NULL,
  email TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending','sent','clicked','reviewed','skipped')),
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_blog_post_status ON blog_post(status);
CREATE INDEX IF NOT EXISTS idx_blog_post_slug ON blog_post(slug);
CREATE INDEX IF NOT EXISTS idx_subscriber_email ON marketing_subscriber(email);
CREATE INDEX IF NOT EXISTS idx_social_post_status ON social_post(status, scheduled_at);
CREATE INDEX IF NOT EXISTS idx_chat_session ON chat_message(session_id, created_at);
CREATE INDEX IF NOT EXISTS idx_review_account ON review_request(account_id);

-- RLS
ALTER TABLE blog_post ENABLE ROW LEVEL SECURITY;
ALTER TABLE marketing_subscriber ENABLE ROW LEVEL SECURITY;
ALTER TABLE social_post ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_message ENABLE ROW LEVEL SECURITY;
ALTER TABLE review_request ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Service role full access" ON blog_post FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON marketing_subscriber FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON social_post FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON chat_message FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Service role full access" ON review_request FOR ALL USING (true) WITH CHECK (true);
