package ebs;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.math.BigDecimal;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.security.InvalidKeyException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.PublicKey;
import java.security.cert.CertificateFactory;
import java.security.cert.X509Certificate;
import java.text.SimpleDateFormat;
import java.util.Base64;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
import java.util.UUID;

import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.KeyGenerator;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;

import org.json.JSONObject;

import com.fasterxml.jackson.databind.ObjectMapper;

import ebs.exceptions.CertificateException;
import ebs.models.Invoice;
import ebs.models.response.AuthenticateResponse;
import ebs.models.response.TransmitInvoiceResponse;

public class EbsMraClient {
	
	private String username, password, ebsMraId, areaCode;
	private String token, tokenExpiryDate, secretKey; //generated by mra
	private TokenRepository tokenRepository;
	
	public EbsMraClient(String username, String password, String ebsMraId, String areaCode) {
		this.username = username;
		this.password = password;
		this.ebsMraId = ebsMraId;
		this.areaCode = areaCode;
	}
	
	public EbsMraClient(String username, String password, String ebsMraId, String areaCode, TokenRepository tokenRepository) {
		this(username, password, ebsMraId, areaCode);
		this.tokenRepository = tokenRepository;
	}
	
	public void setTokenInfo(String token, String tokenExpiryDate, String secretKey) {
		this.token = token;
		this.tokenExpiryDate = tokenExpiryDate;
		this.secretKey = secretKey;
	}
	
	/**
	 * https://vfisc.mra.mu/einvoice-token-service/token-api/generate-token
	 * @return 
	 * @throws Exception 
	 */
	public AuthenticateResponse authenticate(boolean refreshToken) throws Exception {
		
		String encryptKey = generateRandomAESkey();
		
		JSONObject payloadInput = new JSONObject();
		payloadInput.put("username", username);
		payloadInput.put("password", password);
		payloadInput.put("encryptKey", encryptKey);
		payloadInput.put("refreshToken", refreshToken ? "true" : "false");
		
		//encrypt payload input		
		String payload = encodeToBase64(encryptUsingMraRSACertificate(CERTIFICATE, payloadInput.toString()));
		
		//construct request payload
		JSONObject body = new JSONObject();
		body.put("requestId", UUID.randomUUID().toString());
		body.put("payload", payload);		
		
		Map<String, String> headers = new HashMap<String, String>();
		headers.put("username", username);
		headers.put("ebsMraId", ebsMraId);
		headers.put("areaCode", areaCode);
		
		String url = "https://vfisc.mra.mu/einvoice-token-service/token-api/generate-token";
		
		String response = _post(url, headers, body.toString());
		
		ObjectMapper objectMapper = new ObjectMapper();
		
		AuthenticateResponse tokenResponse = objectMapper.readValue(response, AuthenticateResponse.class);
		
		//decrypt key returned by mra
		if("SUCCESS".equalsIgnoreCase(tokenResponse.getStatus())) {
			
			String encryptedSecretKey = tokenResponse.getKey();
			String decryptedSecretKey = decryptTokenKey(encryptKey, encryptedSecretKey);
			
			tokenResponse.setKey(decryptedSecretKey);			
			
			this.setTokenInfo(tokenResponse.getToken(), tokenResponse.getExpiryDate(), tokenResponse.getKey());
			
			if(tokenRepository != null) {
				
				tokenRepository.setToken(this.token);
				tokenRepository.setTokenExpiryDate(this.tokenExpiryDate);
				tokenRepository.setSecretKey(this.secretKey);
				
				tokenRepository.save();
			}
		}		
		
		return tokenResponse;
	}
	
	public byte[] encryptUsingMraRSACertificate(String message) throws Exception {
		
		String path = System.getProperty("MRA_PUBLIC_KEY_CERTIFICATE_PATH", "");
		
		if(path.length() == 0) {
			throw new CertificateException("Environment variable: MRA_PUBLIC_KEY_CERTIFICATE_PATH not found!");
		}
		
		File f = new File(path);
		if(!f.exists()) {
			throw new CertificateException(String.format("Certificate %s not found!", path));
		}
		
		FileInputStream fileInputStream = new FileInputStream(f);

		CertificateFactory cf = CertificateFactory.getInstance("X.509");
		X509Certificate cert = (X509Certificate)cf.generateCertificate(fileInputStream);
		PublicKey publicKey = cert.getPublicKey();
		
		byte[] messageToBytes = message.getBytes();
        Cipher cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding");
        cipher.init(Cipher.ENCRYPT_MODE, publicKey);
        
        return cipher.doFinal(messageToBytes);
	}
	
	public byte[] encryptUsingMraRSACertificate(String certificate, String message) throws Exception {
		
		byte[] decodedCertificate = decodeFromBase64(certificate);
		
		CertificateFactory cf = CertificateFactory.getInstance("X.509");
	    X509Certificate cert = (X509Certificate) cf.generateCertificate(new ByteArrayInputStream(decodedCertificate));

		PublicKey publicKey = cert.getPublicKey();
		
		byte[] messageToBytes = message.getBytes();
        Cipher cipher = Cipher.getInstance("RSA/ECB/PKCS1Padding");
        cipher.init(Cipher.ENCRYPT_MODE, publicKey);
        
        return cipher.doFinal(messageToBytes);
	}
	
	public String generateRandomAESkey() throws Exception {
		
		// Generate a random 256-bit (32-byte) AES key
        KeyGenerator keyGenerator = KeyGenerator.getInstance("AES");
        keyGenerator.init(256);
        SecretKey secretKey = keyGenerator.generateKey();

        // Convert the AES key to a byte array
        byte[] keyBytes = secretKey.getEncoded();

        // Encode the keyBytes as a Base64 string
        String base64EncodedKey = encodeToBase64(keyBytes);
        
        return base64EncodedKey;
	}
	
	public String decryptTokenKey(String secretKey, String encryptedTokenKey) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException, IllegalBlockSizeException, BadPaddingException {
		
		SecretKeySpec spec = new SecretKeySpec(decodeFromBase64(secretKey), "AES");
		
		Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5Padding");
        cipher.init(Cipher.DECRYPT_MODE, spec);
        
        // Decode the Base64-encoded encrypted key
        byte[] encryptedKeyBytes = decodeFromBase64(encryptedTokenKey);
		
        // Decrypt the encrypted key using the AES key
        byte[] decryptedKeyBytes = cipher.doFinal(encryptedKeyBytes);

        // Convert the decrypted key bytes to a string
        String decryptedKey = new String(decryptedKeyBytes, StandardCharsets.UTF_8);
        
        return decryptedKey;
	}
	
	public String encrypt(String base64EncodedSecretKey, String data) throws NoSuchAlgorithmException, NoSuchPaddingException, InvalidKeyException, IllegalBlockSizeException, BadPaddingException {
		
		// Decode the Base64-encoded AES key
        byte[] aesKeyBytes = decodeFromBase64(base64EncodedSecretKey);
		SecretKey aesKey = new SecretKeySpec(aesKeyBytes, "AES");
		
		Cipher cipher = Cipher.getInstance("AES/ECB/PKCS5PADDING");
        cipher.init(Cipher.ENCRYPT_MODE, aesKey);
        
        byte[] b = cipher.doFinal(data.getBytes());
        
		return encodeToBase64(b);
	}
	
	public static String previousNoteHash(String dateTime, BigDecimal totalAmtPaid, String brn, String invoiceIdentifier) throws NoSuchAlgorithmException {
	    
		StringBuffer sb = (new StringBuffer(dateTime)).append(totalAmtPaid).append(brn).append(invoiceIdentifier);
	    String concatenated_value = sb.toString();
	    
	    MessageDigest md = MessageDigest.getInstance("SHA-256");
	    
	    byte[] bytes = md.digest(concatenated_value.getBytes());
	    sb = new StringBuffer();
	    byte b;
	    int i;
	    byte[] arrayOfByte1;
	    
	    for (i = (arrayOfByte1 = bytes).length, b = 0; b < i; ) {
	      byte b1 = arrayOfByte1[b];
	      sb.append(String.format("%02X", new Object[] { Byte.valueOf(b1) }));
	      b++;
	    } 
	    
	    String previousNoteHash = sb.toString();
	    return previousNoteHash;
	}
	
	public void validateToken() {
		
	}
		
	//------------- transmit invoice -------------//
	public TransmitInvoiceResponse transmitInvoice(Invoice[] invoices) throws Exception {
		
		ObjectMapper objectMapper = new ObjectMapper();
		
		String invoiceJson = objectMapper.writeValueAsString(invoices);
		
		String encryptedInvoice;
		
		try 
		{
			encryptedInvoice = encrypt(secretKey, invoiceJson);
		} 
		catch (Exception e) 
		{
			throw e; 
		} 
		
		SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd HH:mm:ss");
		
		JSONObject body = new JSONObject();
		body.put("requestId", UUID.randomUUID().toString());
		body.put("requestDateTime", sdf.format(new Date()));
		body.put("encryptedInvoice", encryptedInvoice);
		
		Map<String, String> headers = new HashMap<String, String>();
		headers.put("username", username);
		headers.put("ebsMraId", ebsMraId);
		headers.put("areaCode", areaCode);
		headers.put("token", token);
		
		String url = "https://vfisc.mra.mu/realtime/invoice/transmit";
		
		String response = _post(url, headers, body.toString());				
		
		return objectMapper.readValue(response, TransmitInvoiceResponse.class);
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEbsMraId() {
		return ebsMraId;
	}

	public void setEbsMraId(String ebsMraId) {
		this.ebsMraId = ebsMraId;
	}

	public String getAreaCode() {
		return areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getTokenExpiryDate() {
		return tokenExpiryDate;
	}

	public void setTokenExpiryDate(String tokenExpiryDate) {
		this.tokenExpiryDate = tokenExpiryDate;
	}

	public String getSecretKey() {
		return secretKey;
	}

	public void setSecretKey(String secretKey) {
		this.secretKey = secretKey;
	}

	public TokenRepository getTokenRepository() {
		return tokenRepository;
	}

	public void setTokenRepository(TokenRepository tokenRepository) {
		this.tokenRepository = tokenRepository;
		
		if(this.tokenRepository != null) {			
			this.tokenRepository.load();
			this.setTokenInfo(this.tokenRepository.getToken(), this.tokenRepository.getTokenExpiryDate(), this.tokenRepository.getSecretKey());
		}
	}	
	
	//--- some helper methods ---
	private String _post(String url, Map<String, String> headers, String requestBody) throws Exception {
		
		try 
		{
            HttpURLConnection connection = (HttpURLConnection) new URL(url).openConnection();
            
            connection.setRequestMethod("POST");
            connection.setRequestProperty("Content-Type", "application/json");
            
            for(Entry<String, String> entry : headers.entrySet()) {
            	connection.setRequestProperty(entry.getKey(), entry.getValue());
            }            

            // Enable input/output streams for sending/receiving data
            connection.setDoOutput(true);

            // Write the request body
            OutputStream os = connection.getOutputStream();
            byte[] input = requestBody.getBytes("utf-8");
            os.write(input, 0, input.length);
            os.flush();
            os.close();

            // Get the response code
            int responseCode = connection.getResponseCode();

            BufferedReader in;
            if (responseCode >= 400) {
                // For 4xx and 5xx status codes, read error stream
                in = new BufferedReader(new InputStreamReader(connection.getErrorStream()));
            } else {
                // For 2xx status codes, read input stream
                in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
            }

            String inputLine;
            StringBuilder response = new StringBuilder();

            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();            

            connection.disconnect();
            
            return response.toString();
        } 
		catch (Exception e) {
            throw e;
        }
	}
	
	// Encode a byte array to Base64
    public String encodeToBase64(byte[] input) {
        return Base64.getEncoder().encodeToString(input);
    }

    // Decode a Base64 string to a byte array
    public byte[] decodeFromBase64(String input) {
        return Base64.getDecoder().decode(input);
    }
	
	//static final String CERTIFICATE = "MIIHyDCCBrCgAwIBAgIQB9ygjZ+YdqS7ERdjcLWwwTANBgkqhkiG9w0BAQ0FADBZMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMTMwMQYDVQQDEypEaWdpQ2VydCBHbG9iYWwgRzIgVExTIFJTQSBTSEEyNTYgMjAyMCBDQTEwHhcNMjMwNTIyMDAwMDAwWhcNMjQwMzEyMjM1OTU5WjBfMQswCQYDVQQGEwJNVTETMBEGA1UEBxMKUG9ydCBMb3VpczEkMCIGA1UEChMbTWF1cml0aXVzIFJldmVudWUgQXV0aG9yaXR5MRUwEwYDVQQDEwx2ZmlzYy5tcmEubXUwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCarsTAIeMek52K8SCbH2jD84fmIXjSHohXZU/GSgVfEBnwk2WvZXeJfkRMSWU4vdDJlsTDi0luDg5oArCWrZldiVpfpegXDj+daNVzj4d3QP/HgI02Q/+7yKRIV42orUXbyVDXqqukLW/JvGpzwHD4D4KbnV/3hjMxeMiQo7Yb08T+kytKcPdZWKyu85MXwaA/dBtkpkaXunYMRYqewLdJBbFK7QcI/mQ+1jxCS+F4IMSqGj+0Qct9V3MgXKEzh9iATDfXxejHrF5J59etSleRZBkIat2NPQ5n07miTpgVq1z33H8sjc44CXbJCemM1IzZD/IwiB2WNZaG2NaqSoQrUHrlIcrDRcz++nrtVvjLsrh1NZ8fIGvd+DkLrQ4HexI/k+rpSu2sh7C6AD1XkbhQwKD9rchNIgXQXuOVrQC4XpPHzjiqHRIAebSbnzdANV7NsnaTt1hslzLF995yi3RKcVoSiULUPJxWQLxO5evx9GpsoYc3zk9Hfdupa7m+i786Riqn5cLoYfr6XbPTKDZuQwavsiN+5h/7YR5KwFoeGzSWB00dBBSKoU4Cu2VWmjhaSritCKUcOP5T65PkKOsAFbz2CkqYWS8mSWksEKOi6YOwFkV1oqwI8sTbL5Cgdaxd1szqQcwgup2xfOx737Fi4JXdi/DXC3DyNqbmUJXO0wIDAQABo4IDhDCCA4AwHwYDVR0jBBgwFoAUdIWAwGbH3zfez70pN6oDHb7tzRcwHQYDVR0OBBYEFF6twzXWvLU6IDuYN5KJP8/tQbXnMBcGA1UdEQQQMA6CDHZmaXNjLm1yYS5tdTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMIGfBgNVHR8EgZcwgZQwSKBGoESGQmh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbEcyVExTUlNBU0hBMjU2MjAyMENBMS0xLmNybDBIoEagRIZCaHR0cDovL2NybDQuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0R2xvYmFsRzJUTFNSU0FTSEEyNTYyMDIwQ0ExLTEuY3JsMD4GA1UdIAQ3MDUwMwYGZ4EMAQICMCkwJwYIKwYBBQUHAgEWG2h0dHA6Ly93d3cuZGlnaWNlcnQuY29tL0NQUzCBhwYIKwYBBQUHAQEEezB5MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wUQYIKwYBBQUHMAKGRWh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbEcyVExTUlNBU0hBMjU2MjAyMENBMS0xLmNydDAJBgNVHRMEAjAAMIIBfQYKKwYBBAHWeQIEAgSCAW0EggFpAWcAdQDuzdBk1dsazsVct520zROiModGfLzs3sNRSFlGcR+1mwAAAYhCAvCvAAAEAwBGMEQCICRU4lR6J5qIihmYlqnDTMX9P9NC++VymyylTo1Yg0XZAiBvZRwal2xqbjfy7fq1i/ZDCAWmkXU1J6AkeFOBJk9AZgB3AEiw42vapkc0D+VqAvqdMOscUgHLVt0sgdm7v6s52IRzAAABiEIC8K8AAAQDAEgwRgIhAMICQR/sNMV9fCWzCZavY160XjNjRl7vaH2e+Mupb30lAiEA4zjUoYssOJN85Tcq4D/QC88JZ6Ka8XFAaKbQpA1REncAdQDatr9rP7W2Ip+bwrtca+hwkXFsu1GEhTS9pD0wSNf7qwAAAYhCAvB5AAAEAwBGMEQCIACPzUMLqQTkyf1+++GJhu8FmErQCql32vVMZTogAA/sAiAWuNAX4ruLNMhhen2oqR6ICQyvUbnLrrvSLA2bilw2jTANBgkqhkiG9w0BAQ0FAAOCAQEAG+S2fY7QCVv1GzLLZ3JCryzY10MOsY4h1hubVgvHUX5IaWX5qjqX+yBwWdeXg3vSDb+HnBY3b3SRb7Grl1Vy/N3DQ0zyD2pzL3w78JO7VjJVTkH7aJmpryXHWMjx+2whZ/K4jOvXhOlFyeXMtDFAcpNXZNcdQ1hfivVf3/i8cU1tsB1Om/ZcfoawE7DeSOW+0Tzvq0PzFft2t60apn1F7MrSSwpJVDAHJLwQS6N7SFs3M+lNLpGGylpxiVHrFW446pxpRgglqvbmxAyE0/mMJWl36KUez1ni7z+EoDQfz1eXWI0d8zhtempJV+oZc/KF7it56vcaSHnSn3wucXQxuw==";
    static final String CERTIFICATE = "MIIFyTCCA7GgAwIBAgIIVF/OBiAkSmYwDQYJKoZIhvcNAQEMBQAwgZIxCzAJBgNVBAYTAk1VMRMwEQYDVQQIEwpQb3J0IExvdWlzMRMwEQYDVQQHEwpQb3J0IExvdWlzMSQwIgYDVQQKExtNYXVyaXRpdXMgUmV2ZW51ZSBBdXRob3JpdHkxGzAZBgNVBAsTEkluZm9ybWF0aW9uIFN5c3RlbTEWMBQGA1UEAxMNZWludnNzLm1yYS5tdTAeFw0yNTAzMjUwNTExNTFaFw0yODAzMjQwNTExNTFaMIGSMQswCQYDVQQGEwJNVTETMBEGA1UECBMKUG9ydCBMb3VpczETMBEGA1UEBxMKUG9ydCBMb3VpczEkMCIGA1UEChMbTWF1cml0aXVzIFJldmVudWUgQXV0aG9yaXR5MRswGQYDVQQLExJJbmZvcm1hdGlvbiBTeXN0ZW0xFjAUBgNVBAMTDWVpbnZzcy5tcmEubXUwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC1v2clNq7fmTkaG5uDehYLqeGC5TS4ggaw/aUKp0AFbICVlqTdRCrclviCD6fDCSl0hfFm1m0UvekGU+ATIDvQ0DkKSzItywK1n77kx1D/VUubFlBiWZC1kjwQbwggoeIrXxeJ4qfjkrBZGHZFnxXiXp9FYb4jy8kP1r4gXn2fqqpL6Squ3ek3JpRmmGzUupBspAS8fBBd6+GvlisxrKuNxoyRpiCzfIcglagEIJimcbr/7wmiA1yo7wvt1RLZyhymmlX6KXu8BtjG/NjlhQYvlVxMbt0kNHYbIlMIz8xflY+E8qvN+Sba63AIgqc2dvQymj4oG7RDu+nWFZkJAQprWCo08ezllJ68ybHq+AcvvfJEcYaXU/wNs5S9kwgFf2QyoUt+z6d8VdlAACqcw+6MijCpGrV7aIVxQnd+TAh1yexmkaeaPy+PH4IZLkDhfSYWVb88aZ5vRT6i7mc8y1fOsLEew5kBOHYzdo90Rfh6d+bm9vjaMquWT1ojwJ4nmIjU2dFu9M4Gy6urukL8ef3QjZYLcdQ9j5jd+m22dVjK3GphMruqjplTARl0fMc0vpHRxHfGm+RSkBP4NZkyS7/8U1X0MNdKo9sJftsICk3TB2BMqs5mCki14sQ8v0QK6CQc7i9IinQRs/ikios5w2NSk/Tp8qc70xTR7ysOuxPumwIDAQABoyEwHzAdBgNVHQ4EFgQUZ+8OZ+pcYCeuergF33dyTyyFFIMwDQYJKoZIhvcNAQEMBQADggIBAGOtu5VkQFV09hUIwUhke5hNeDnyxal5iTyJCmKOKNL1O5U7+iMaiCwNAjJZB6To4XKHU0YPMSnY56Ghg3QtgLOdnZxKBy8D/5DHBVsD2HIO6TSTfORvDRvl+yGML6t9kWsXDhlDPRdyhB9VzwpirkylMvpXt9VL7Wbix20C6xXPIjIYc5cC4pzVQXOjTlWXgrgnTadUtrSqkYGRrpUiSSeurXisPSKzTNqIpUFQ9L9q1Vf5MpszvG+LOHq1hJ+3jD1HDky6hfD3TPy0zT/6Be4K8WT7miWI7vRApyamDvpjMpjdwa5F1lq++7xC6+cyj2W6Ebhda8RV9a2ilkJcKrRBfuaXfYQLZ1fzURxRWHyAl/1pgaSsO8Pcq1V9ki5Wrbz7hf0KrlF0RohfUJAM1fNMYQOmoBXzlDC6wTwFRSZJZHPytgADC/7wIP0/FuOninyEouJykyqJrYRxAQ+cAv53SsSDhk7hZomxkh3H+iiSMxRYODmktaZs8UQS/iHY6PhilBApaNb+PmcRuedn/RElwzFlpq45VGHoPUy1zpAOpXiIGgpVdujd+ec7+Hznpgn6I5LCLtq+ZrNN1LmXUhw6z8CERgxYKr5U6otqaiJDULiuW2qVz2u7pDfMlBO+DuS9+44gSRNdGEEmMnyQ2kStqoeb/zJZczrqFRgRLUoh";
}
