export const TEST_SUITES = {
  android: {
    totalTests: 419,
    totalFiles: 21,
    allPassed: true,
    lastVerified: "2026-03-23",
    version: "Room v25, Kotlin",
    files: [
      { name: "CartItemTest", tests: 12, area: "Tax calc, discount, clone" },
      { name: "CartRecalculationTest", tests: 24, area: "Totals, discount on total, qty tracking" },
      { name: "CartSerializationTest", tests: 24, area: "JSON serialize/restore, modifiers" },
      { name: "CloudSyncFieldMappingTest", tests: 17, area: "Camel→snake field mapping" },
      { name: "CloudSyncIntegrationTest", tests: 6, area: "Full sync round-trip" },
      { name: "DateUtilsTest", tests: 7, area: "Date formatting, parsing" },
      { name: "DiscountCalculationTest", tests: 11, area: "Percentage, fixed, stacking" },
      { name: "HoldOrderFlowTest", tests: 19, area: "Hold/recall/delete, table assignment" },
      { name: "KitchenOrderFlowTest", tests: 27, area: "Status cycle, split, merge, stations" },
      { name: "LoyaltyRepositoryTest", tests: 34, area: "Points, cache, offline queue, tiers" },
      { name: "NumberUtilsTest", tests: 16, area: "Price/qty formatting, parsing" },
      { name: "OrderDetailsTest", tests: 15, area: "OrderDetails build, JSON round-trip" },
      { name: "OrderFormattingTest", tests: 44, area: "Receipt, kitchen copy, till receipt" },
      { name: "PaymentCalculationTest", tests: 25, area: "Cash/card/split, change, rounding" },
      { name: "SecurityTest", tests: 10, area: "PIN validation, session timeout" },
      { name: "ShoppingCartTest", tests: 31, area: "Add/remove/clear, qty update" },
      { name: "SyncContractTest", tests: 12, area: "Request/response schema" },
      { name: "SyncRegressionTest", tests: 16, area: "Field mapping bugs, null handling" },
      { name: "SyncStatusManagerTest", tests: 24, area: "State transitions, summary" },
      { name: "TableManagementTest", tests: 19, area: "Table CRUD, occupancy, sections" },
      { name: "TaxCalculationTest", tests: 26, area: "Inclusive/exclusive, fixed, multi-rate" },
    ],
  },
  smoke: {
    totalTests: 42,
    totalFiles: 1,
    allPassed: true,
    lastVerified: "2026-03-23",
    version: "Vitest 4.1, hits production",
    files: [
      { name: "smoke-test.test.ts", tests: 42, area: "API health, DB tables, data integrity, sync contract, web pages, edge cases, SQL injection" },
    ],
  },
  adb: {
    totalTests: 8,
    totalFiles: 1,
    allPassed: true,
    lastVerified: "2026-03-23",
    version: "ADB + uiautomator, XML hierarchy",
    files: [
      { name: "adb-smoke-test.sh", tests: 8, area: "App launch, crash detection, connectivity, UI nodes, ANR, memory, DB, logcat" },
    ],
  },
  web: {
    totalTests: 156,
    totalFiles: 13,
    allPassed: true,
    lastVerified: "2026-03-23",
    version: "Vitest 4.1, Next.js 16",
    files: [
      { name: "ai-import.test.ts", tests: 2, area: "AI product discovery" },
      { name: "business-logic.test.ts", tests: 14, area: "FK ordering, precision, filtering" },
      { name: "data-api.test.ts", tests: 15, area: "Table whitelist, batch, filters" },
      { name: "e2e-integration.test.ts", tests: 27, area: "Full signup→login→sync→OTT→enroll" },
      { name: "owner-accounts.test.ts", tests: 4, area: "Owner listing, update, delete" },
      { name: "platform-create-account.test.ts", tests: 6, area: "Super admin, validation" },
      { name: "register-edge-cases.test.ts", tests: 16, area: "Empty arrays, camelCase, re-register" },
      { name: "schema-validation.test.ts", tests: 7, area: "Field mapping, UUID preservation" },
      { name: "security.test.ts", tests: 5, area: "Missing fields, malformed JSON" },
      { name: "signup.test.ts", tests: 13, area: "Owner+brand creation, auth linking" },
      { name: "sync.test.ts", tests: 15, area: "Push/pull, validation, payments" },
      { name: "sync-edge-cases.test.ts", tests: 21, area: "Batch, null fields, insertOrUpdate" },
      { name: "sync-register.test.ts", tests: 10, area: "Registration, demo accounts" },
    ],
  },
};
